### PR TITLE
feat: Add Protocol v1.3

### PR DESCRIPTION
**Pull request by ExE-Boss**
This&nbsp;adds compatibility&nbsp;data for&nbsp;the&nbsp;**Chrome Debugger&nbsp;Protocol&nbsp;v1.3**, which&nbsp;**Firefox** is&nbsp;implementing in&nbsp;[bug&nbsp;1523097](https://bugzilla.mozilla.org/show_bug.cgi?id=1523097 "1523097 - (puppeteer) [meta] Puppeteer support"), with&nbsp;support&nbsp;information&nbsp;obtained from&nbsp;[mozilla‑central@`ad62341`:&nbsp;/remote⁠/Protocol.jsm](https://searchfox.org/mozilla-central/rev/ad6234148892bc29bf08d736604ac71925138040/remote/Protocol.jsm).

### CODE REVIEW

**Comment by auchenberg** [comment]
LGTM

**Comment by auchenberg** [comment]
Deployed. Thanks a bunch @ExE-Boss

**Comment by auchenberg** [comment]
Looking at the protocol.json provided by Mozilla it seems that it's completely wrong, so gotta revert. https://searchfox.org/mozilla-central/rev/ad6234148892bc29bf08d736604ac71925138040/remote/Protocol.jsm#11 @ExE-Boss

**Comment by ExE-Boss** [comment]
You&nbsp;could’ve just&nbsp;removed the&nbsp;**Firefox**&nbsp;information, because&nbsp;the&nbsp;**Chrome** and&nbsp;**Node** ones&nbsp;are&nbsp;accurate.

**Pull request merged**
